name: Deploy Power BI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests msal

    - name: Deploy Power BI .pbix file
      id: deploy_powerbi
      env:
        POWERBI_CLIENT_ID: ${{ secrets.POWERBI_CLIENT_ID }}
        POWERBI_CLIENT_SECRET: ${{ secrets.POWERBI_CLIENT_SECRET }}
        POWERBI_TENANT_ID: ${{ secrets.POWERBI_TENANT_ID }}
        POWERBI_WORKSPACE_ID: ${{ secrets.POWERBI_WORKSPACE_ID }}
      run: |
        python deploy_powerbi.py || echo "error_message=$(error.log)" >> $GITHUB_ENV
      continue-on-error: false

    - name: Check for errors
      if: steps.deploy_powerbi.outputs.error_message != ''
      run: |
        echo "Error during deployment: ${{ env.error_message }}"
        exit 1